apiVersion: v1
kind: Service
metadata:
  name: prom-public-svc
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: k8s
  ports:
    - name: http-web
      protocol: TCP
      port: 9090
      targetPort: 9090
