---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      app: {{.name}}-{{.Replica}}
      svc: {{.name}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: {{.name}}-{{.Replica}}
        svc: {{.name}}-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - args:
        - sleep
        - infinity
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 39m
            memory: 138MiB
        volumeMounts:
          - name: configmap
            mountPath: /var/configmap
          - name: secret
            mountPath: /var/secret
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080
           protocol: TCP
        name: {{.name}}-1-{{.Replica}}
        env:
        - name: ENVVAR1_{{.name}}
          value: {{.envVar}}
      - args:  # Container 2 definition
        - sleep
        - infinity
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 39m
            memory: 138MiB
        volumeMounts:
          - name: configmap
            mountPath: /var/configmap
          - name: secret
            mountPath: /var/secret
        ports:
         - containerPort: 8080
           protocol: TCP
        name: {{.name}}-2-{{.Replica}}
        env:
        - name: ENVVAR1_{{.name}}
          value: {{.envVar}}
      - args:  # Container 3 definition
        - sleep
        - infinity
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 39m
            memory: 138MiB
        volumeMounts:
          - name: configmap
            mountPath: /var/configmap
          - name: secret
            mountPath: /var/secret
        ports:
         - containerPort: 8080
           protocol: TCP
        name: {{.name}}-3-{{.Replica}}
        env:
        - name: ENVVAR1_{{.name}}
          value: {{.envVar}}
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      volumes:
        - name: configmap
          configMap:
            name: configmap-{{.Replica}}
        - name: secret
          secret:
            secretName: secret-{{.Replica}}
