---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}-{{.Replica}}
      svc: {{.name}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: {{.name}}-{{.Replica}}
        svc: {{.name}}-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: {{.name}}-0-{{.Replica}}
        args:
        - sleep
        - infinity
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 63m
            memory: 224Mi
        volumeMounts:
        - name: secret-{{.Replica}}
          mountPath: /secret1
        - name: configmap-{{.Replica}}
          mountPath: /configmap1
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080
           protocol: TCP
        env:
        - name: ENVVAR1_{{.name}}
          value: {{.envVar}}
      - name: {{.name}}-1-{{.Replica}}
        args:
        - sleep
        - infinity
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 39m
            memory: 138Mi
        volumeMounts:
        - name: secret-{{.Replica}}-1
          mountPath: /secret1
        - name: configmap-{{.Replica}}-1
          mountPath: /configmap1
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080
           protocol: TCP
        env:
        - name: ENVVAR1_{{.name}}
          value: {{.envVar}}
      volumes:
      - name: secret-{{.Replica}}
        secret:
          secretName: {{.name}}-secret0-{{.Replica}}
      - name: secret-{{.Replica}}-1
        secret:
          secretName: {{.name}}-secret1-{{.Replica}}
      - name: configmap-{{.Replica}}
        configMap:
          name: {{.name}}-cm0-{{.Replica}}
      - name: configmap-{{.Replica}}-1
        configMap:
          name: {{.name}}-cm1-{{.Replica}}
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
