kind: Pod
apiVersion: v1
metadata:
  name: {{.name}}-{{.Replica}}
  labels:
    name: {{.name}}-{{.Replica}}
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  containers:
  - name: hcp-density-aks
    image:  registry.k8s.io/pause:3.1
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
    volumeMounts:
    - name: configmap
      mountPath: /var/configmap
    - name: secret
      mountPath: /var/secret
  volumes:
  - name: configmap
    configMap:
      name: configmap-{{.Replica}}
  - name: secret
    secret:
      secretName: secret-{{.Replica}}