kind: Service
apiVersion: v1
metadata:
  name: {{.name}}-{{.Replica}}
spec:
  selector:
    name: {{.name}}-{{.Replica}}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP